### ISSUE TITLE
Modify mock data for tests

### ISSUE THREAD

**Issue by c-georgen** [Topl/BramblJS#54]

**Comment by raularagonez** [comment]
Brambl
    new brambl()
      ✓ should pass by passing password and networkPrefix
      ✓ should default empty network prefix to private
      ✓ should fail is trying to set network prefix outside of constructor
      ✓ should fail with invalid network prefix
      ✓ should fail if Requests and KeyManager instances NetworkPrefixes don't match
      valid network prefixes
        ✓ should pass if network prefix is local
        ✓ should pass if network prefix is local | diff url
        ✓ should pass if network prefix is local | diff url | diff apiKey
        ✓ should pass if network prefix is private
        ✓ should pass if network prefix is private | diff url
        ✓ should pass if network prefix is private | diff url | diff apiKey
        ✓ should pass if network prefix is toplnet
        ✓ should pass if network prefix is toplnet | diff url
        ✓ should pass if network prefix is toplnet | diff url | diff apiKey
        ✓ should pass if network prefix is valhalla
        ✓ should pass if network prefix is valhalla | diff url
        ✓ should pass if network prefix is valhalla | diff url | diff apiKey
        ✓ should pass if network prefix is hel
        ✓ should pass if network prefix is hel | diff url
        ✓ should pass if network prefix is hel | diff url | diff apiKey

  KeyManager
    new keymanager()
      invalid passwords
        ✓ should fail if password is 123
        ✓ should fail if password is []
        ✓ should fail if password is {}
        ✓ should fail if password is 5.12
        ✓ should fail if password is [[]]
        ✓ should fail if password is undefined
        ✓ should fail if password is {password:123}
        ✓ should fail if password is {password:[]}
        ✓ should fail if password is {password:undefined}
        ✓ should fail if password is {invalidPasswordKey:'invalidKey'}
      generate key w/ valid password
        ✓ should generate key using password passwordtest
        ✓ should generate key using password this_is_a_password
        ✓ should generate key using password !@#$%^&*(_special_@#$2021
      generate key w/ keypath
        ✓ should instantiate using keyPath this_is_a_password
        ✓ should instantiate using keyPath !@#$%^&*(_special_@#$2021
    lockKey()
      ✓ should pass if lockKey getter returns boolean
      ✓ should fail if lockKey setter called
      ✓ should lock key
      ✓ should fail to unlock key with invalid password
      ✓ should fail to unlock key with invalid password
      ✓ should unlock key with valid password
      ✓ should throw error if key already unlocked
    unlockKey()
      ✓ should set isLocked to false when unlocked
      ✓ should fail if key is already unlocked
      ✓ should fail if unlocking with incorrect password
    getKeyStorage()
      ✓ should pass if key is unlocked
      ✓ should fail if key is locked
    sign()
      ✓ should fail if key is locked
      ✓ should fail if message is empty
      ✓ should fail if message is not a string
      ✓ should pass if message is a string
    Getters()
      ✓ should pass get isLocked()
      ✓ should pass get pk()
      ✓ should pass get address()
      ✓ should pass get networkPrefix()
    setters()
      ✓ should fail set isLocked()
      ✓ should fail set pk()
      ✓ should fail set address()
      ✓ should fail set networkPrefix()
    exportToFile()
      ✓ should fail if key is locked
      ✓ should fail if keypath param is []
      ✓ should fail if keypath param is {"keyPath":"invalid key"}
      ✓ should pass if keypath param not provided
      ✓ should pass if dir .keypath exists
      ✓ should pass if dir .keypath exists
      ✓ should pass with path.keyfiles/.keyfiles_2021-03-04T23:06:04.724Z0
      ✓ should pass with path.keyfiles/.keyfiles_2021-03-04T23:06:04.724Z1
      ✓ should pass with path.keyfiles/.keyfiles_2021-03-04T23:06:04.724Z2
      ✓ should pass with path.keyfiles/.keyfiles_2021-03-04T23:06:04.724Z3
      ✓ should pass with path.keyfiles/.keyfiles_2021-03-04T23:06:04.724Z4

  Arbits
    create raw arbit transfer
      ✓ should create raw arbit transfer
      ✓ should fail if no parameters present
      ✓ should fail if invalid propositionType provided
      ✓ should fail if no recipients provided
      ✓ should fail if no changeAddress provided
      ✓ should fail if no consolidationAddress provided
      ✓ should fail if no sender provided
      ✓ should fail if no fee provided
      ✓ should fail if fee < 0

  Assets
    create raw asset transfer
      ✓ should NOT fail if parameters are valid
      ✓ should create raw asset
      ✓ should fail if no parameters present
      ✓ should fail if invalid propositionType provided
      ✓ should fail if no sender provided
      ✓ should fail if no assetCode provided
      ✓ should fail if no recipients provided
      ✓ should fail if no changeAddress provided
      ✓ should fail if no minting provided
      ✓ should fail if no fee provided
      ✓ should fail if fee < 0

  Blocks
    lookup block by id
      ✓ should lookup block by id
      ✓ should fail if no parameters present
      ✓ should fail if no blockId provided
    lookup block by height
      ✓ should lookup block by height
      ✓ should fail if no parameters present
      ✓ should fail if no height provided
      ✓ should fail if height < 1
      ✓ should fail if height is not an Integer
      ✓ should fail if height is a double
    get the latest block in the chain
      ✓ should return latest block in chain

  Polys
    create raw polys transfer
      ✓ should create raw polys transfer
      ✓ should fail if no parameters present
      ✓ should fail if invalid propositionType provided
      ✓ should fail if no recipients provided
      ✓ should fail if no changeAddress provided
      ✓ should fail if no sender provided
      ✓ should fail if no fee provided
      ✓ should fail if fee < 0

  Transactions
    broadcast transaction
      ✓ should broadcast tx
      ✓ should fail if no parameters present
      ✓ should fail if no tx object provided
      ✓ should fail if no signature in tx object provided
      ✓ should fail if tx is missing keys
    get transaction by id
      ✓ should get tx by id
      ✓ should fail if no parameters present
      ✓ should fail if no transactionId provided
    get transaction from Mempool
      ✓ should get tx by id
      ✓ should fail if no parameters present
      ✓ should fail if no transactionId provided
    get mempool
      ✓ should get mempool
    lookup balances
      ✓ should get balances using Addresses list
      ✓ should fail if no parameters present
      ✓ should fail if no addresses provided
      ✓ should fail if addresses is not an array
      ✓ should fail if addresses are invalid


  125 passing (1s)

**Comment by raularagonez** [comment]
All tests are passing now!!!

**Comment by scasplte2** [comment]
nicely done! :octocat:
